version: '3'

networks:
  kong-net:

services:
  kong-database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    networks:
    - kong-net

  migration:
    image: kong:1.1
    command: kong migrations bootstrap
    networks:
    - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
    depends_on:
    - kong-database
    restart: on-failure

  kong:
    image: kong:1.1
    networks:
    - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
    - 8000:8000
    - 8001:8001
    depends_on:
    - migration
    restart: on-failure

  konga:
    image: pantsel/konga:0.14.1
    networks:
    - kong-net
    environment:
      NODE_ENV: production
      TOKEN_SECRET: someRandomeString
    ports:
    - 1337:1337

  my-service:
    build: ./service
    networks:
    - kong-net


